### ISSUE TITLE
Dice evicting itself

### ISSUE THREAD

**Issue by jesstracy** [dmathieu/dice#13]
Hi, when running dice as a job inside the cluster, how do you get around the problems that come from dice draining the node it's currently running on?

When testing in a cluster with only 2 nodes (which I'm sure isn't really the intended use case), this caused a complete outage. Dice was running on Node A. Dice drained and deleted Node B, then when Node C came up, it cordoned/drained Node A. Dice started up again on Node C, flagging all the nodes with "dice=roll" again. It cordoned/drained Node C, and at that point there were no usable nodes left, and it stayed that way until our autoscaler was able to get new nodes up and joined.

But even in typical larger clusters, it seems that dice restarting whenever it drains its own node would make for an endless loop. Have you seen this behavior? It's very possible I am missing something with how it's supposed to be run.
Thanks!!

**Comment by dmathieu** [comment]
Hello there,

Thank you for reporting this! 🌹 

It is expected that the process will at some point stop itself and have to restart. Otherwise, one node would always remain up.
We will only flag nodes if [none already flagged were found](https://github.com/dmathieu/dice/blob/master/controllers/all_nodes_flagger.go#L28), to prevent this kind of issue.

Thinking about it, the behavior you're describing could happen if the node the process is running on is killed second.
Then, both nodes would be flagged. Node A would be killed first, and unflagged node C would be started.
Node B would be killed, and when dice restarts, no nodes are flagged so it tries to reflag everything.
This shouldn't happen in the first place though, as we first drain the node, requiring dice to restart even before the node is killed. So when the process is restarted, node B should be still around.

I'll be looking further into this soon. If you reproduce and can provide more information, that would be very helpful too.

**Comment by dmathieu** [comment]
Closing as stale.
